// src/pages/DiskInfo.tsx
import { useEffect, useState } from 'react'
import { Folder, HeartPulse } from 'lucide-react'
import { invoke } from '@/lib/tauri'
import { progressColor, cn } from '@/lib/utils'
import { PageHeader, CardHeaderTitle } from '@/components/page-header'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

interface DiskItem {
  name: string
  type: string
  total: string
  used: string
  free: string
  fileSystem: string
  usage: number
}

interface DiskHealthItem {
  name: string
  temperature: number
  health: number
  readSpeed: string
  writeSpeed: string
  powerOnHours: string
  powerCycle: number
}

function tempClass(temp: number) {
  if (temp < 50) return 'text-green-500'
  if (temp < 70) return 'text-amber-500'
  return 'text-red-500'
}

function healthVariant(health: number): 'success' | 'warning' | 'destructive' {
  if (health >= 90) return 'success'
  if (health >= 70) return 'warning'
  return 'destructive'
}

export default function DiskInfo() {
  const [diskList, setDiskList] = useState<DiskItem[]>([])
  const [diskHealth, setDiskHealth] = useState<DiskHealthItem[]>([])

  useEffect(() => {
    const fetchDiskInfo = async () => {
      try {
        const [disks, health] = await Promise.all([
          invoke<DiskItem[]>('get_disk_list'),
          invoke<DiskHealthItem[]>('get_disk_health'),
        ])
        setDiskList(disks)
        setDiskHealth(health)
      } catch (error) {
        console.error('获取磁盘信息失败:', error)
      }
    }
    fetchDiskInfo()
  }, [])

  return (
    <div>
      <PageHeader title="硬盘信息" subtitle="磁盘存储与健康状态" />

      <Card>
        <CardHeader>
          <CardHeaderTitle icon={<Folder className="h-4 w-4" />} iconClassName="bg-orange-500/10 text-orange-500" title="磁盘列表" />
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[200px]">磁盘名称</TableHead>
                <TableHead className="w-[100px]">类型</TableHead>
                <TableHead className="w-[120px]">总容量</TableHead>
                <TableHead className="w-[120px]">已使用</TableHead>
                <TableHead className="w-[120px]">可用空间</TableHead>
                <TableHead className="w-[100px]">文件系统</TableHead>
                <TableHead>使用率</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {diskList.map((disk) => (
                <TableRow key={disk.name}>
                  <TableCell>{disk.name}</TableCell>
                  <TableCell>
                    <Badge variant={disk.type === 'SSD' ? 'success' : 'info'}>{disk.type}</Badge>
                  </TableCell>
                  <TableCell>{disk.total}</TableCell>
                  <TableCell>{disk.used}</TableCell>
                  <TableCell>{disk.free}</TableCell>
                  <TableCell>{disk.fileSystem}</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2.5">
                      <Progress value={disk.usage} className="h-2 flex-1" indicatorColor={progressColor(disk.usage)} />
                      <span className="whitespace-nowrap text-[13px] font-semibold">{disk.usage}%</span>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Card className="mt-4">
        <CardHeader>
          <CardHeaderTitle icon={<HeartPulse className="h-4 w-4" />} iconClassName="bg-green-500/10 text-green-500" title="磁盘健康状态" />
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[200px]">磁盘</TableHead>
                <TableHead className="w-[100px]">温度</TableHead>
                <TableHead className="w-[100px]">健康度</TableHead>
                <TableHead className="w-[120px]">读取速度</TableHead>
                <TableHead className="w-[120px]">写入速度</TableHead>
                <TableHead className="w-[120px]">通电时间</TableHead>
                <TableHead>通电次数</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {diskHealth.map((item) => (
                <TableRow key={item.name}>
                  <TableCell>{item.name}</TableCell>
                  <TableCell>
                    <span className={cn(tempClass(item.temperature))}>{item.temperature}°C</span>
                  </TableCell>
                  <TableCell>
                    <Badge variant={healthVariant(item.health)}>{item.health}%</Badge>
                  </TableCell>
                  <TableCell>{item.readSpeed}</TableCell>
                  <TableCell>{item.writeSpeed}</TableCell>
                  <TableCell>{item.powerOnHours}</TableCell>
                  <TableCell>{item.powerCycle}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

// src/views/DiskInfo.vue
<template>
  <div class="disk-info">
    <div class="page-header">
      <div class="page-title-row">
        <h2 class="page-title">硬盘信息</h2>
        <span class="page-subtitle">磁盘存储与健康状态</span>
      </div>
    </div>
    
    <el-card class="info-card" shadow="never">
      <template #header>
        <div class="card-header">
          <div class="card-icon-badge disk">
            <el-icon :size="18"><Folder /></el-icon>
          </div>
          <span>磁盘列表</span>
        </div>
      </template>
      <el-table :data="diskList" style="width: 100%">
        <el-table-column prop="name" label="磁盘名称" width="200" />
        <el-table-column prop="type" label="类型" width="100">
          <template #default="scope">
            <el-tag :type="scope.row.type === 'SSD' ? 'success' : 'info'" size="small">{{ scope.row.type }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="total" label="总容量" width="120" />
        <el-table-column prop="used" label="已使用" width="120" />
        <el-table-column prop="free" label="可用空间" width="120" />
        <el-table-column prop="fileSystem" label="文件系统" width="100" />
        <el-table-column label="使用率">
          <template #default="scope">
            <div class="usage-bar-wrap">
              <el-progress :percentage="scope.row.usage" :color="getProgressColor(scope.row.usage)" :stroke-width="8" :show-text="false" />
              <span class="usage-percent">{{ scope.row.usage }}%</span>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
    
    <el-card class="health-card" shadow="never" style="margin-top: 16px;">
      <template #header>
        <div class="card-header">
          <div class="card-icon-badge health">
            <el-icon :size="18"><FirstAidKit /></el-icon>
          </div>
          <span>磁盘健康状态</span>
        </div>
      </template>
      <el-table :data="diskHealth" style="width: 100%">
        <el-table-column prop="name" label="磁盘" width="200" />
        <el-table-column prop="temperature" label="温度" width="100">
          <template #default="scope">
            <span :class="getTempClass(scope.row.temperature)">{{ scope.row.temperature }}°C</span>
          </template>
        </el-table-column>
        <el-table-column prop="health" label="健康度" width="100">
          <template #default="scope">
            <el-tag :type="getHealthType(scope.row.health)" size="small">{{ scope.row.health }}%</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="readSpeed" label="读取速度" width="120" />
        <el-table-column prop="writeSpeed" label="写入速度" width="120" />
        <el-table-column prop="powerOnHours" label="通电时间" width="120" />
        <el-table-column prop="powerCycle" label="通电次数" />
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { invoke } from '@tauri-apps/api/tauri'

interface DiskItem {
  name: string
  type: string
  total: string
  used: string
  free: string
  fileSystem: string
  usage: number
}

interface DiskHealthItem {
  name: string
  temperature: number
  health: number
  readSpeed: string
  writeSpeed: string
  powerOnHours: string
  powerCycle: number
}

const diskList = ref<DiskItem[]>([])
const diskHealth = ref<DiskHealthItem[]>([])

const getProgressColor = (percentage: number) => {
  if (percentage < 50) return '#3b82f6'
  if (percentage < 80) return '#f59e0b'
  return '#ef4444'
}

const getTempClass = (temp: number) => {
  if (temp < 50) return 'temp-normal'
  if (temp < 70) return 'temp-warning'
  return 'temp-danger'
}

const getHealthType = (health: number) => {
  if (health >= 90) return 'success'
  if (health >= 70) return 'warning'
  return 'danger'
}

const fetchDiskInfo = async () => {
  try {
    const [disks, health] = await Promise.all([
      invoke<DiskItem[]>('get_disk_list'),
      invoke<DiskHealthItem[]>('get_disk_health')
    ])
    diskList.value = disks
    diskHealth.value = health
  } catch (error) {
    console.error('获取磁盘信息失败:', error)
  }
}

onMounted(() => {
  fetchDiskInfo()
})
</script>

<style scoped>
.disk-info {
  color: #334155;
}

.page-header {
  margin-bottom: 20px;
}

.page-title-row {
  display: flex;
  align-items: baseline;
  gap: 12px;
}

.page-title {
  font-size: 22px;
  font-weight: 700;
  color: #1e293b;
  margin: 0;
}

.page-subtitle {
  font-size: 13px;
  color: #64748b;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  color: #1e293b;
  font-size: 15px;
  font-weight: 600;
}

.card-icon-badge {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
}

.card-icon-badge.disk {
  background: rgba(249, 115, 22, 0.1);
  color: #f97316;
}

.card-icon-badge.health {
  background: rgba(34, 197, 94, 0.1);
  color: #22c55e;
}

.temp-normal {
  color: #22c55e;
}

.temp-warning {
  color: #f59e0b;
}

.temp-danger {
  color: #ef4444;
}

.usage-bar-wrap {
  display: flex;
  align-items: center;
  gap: 10px;
  width: 100%;
}

.usage-percent {
  font-size: 13px;
  font-weight: 600;
  color: #334155;
  white-space: nowrap;
}
</style>
