// src/pages/Fan.tsx
import { useCallback, useEffect, useState } from 'react'
import { Fan as FanIcon } from 'lucide-react'
import { invoke } from '@/lib/tauri'
import { useInterval } from '@/hooks/use-interval'
import { PageHeader, CardHeaderTitle } from '@/components/page-header'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

interface FanInfo {
  name: string
  speed: number
  maxSpeed: number
  mode: string
}

function getFanPercentage(speed: number, maxSpeed: number) {
  if (!maxSpeed) return 0
  return Math.round((speed / maxSpeed) * 100)
}

function getFanColor(speed: number, maxSpeed: number) {
  const percentage = maxSpeed ? (speed / maxSpeed) * 100 : 0
  if (percentage < 30) return '#22c55e'
  if (percentage < 70) return '#f59e0b'
  return '#ef4444'
}

export default function Fan() {
  const [fanList, setFanList] = useState<FanInfo[]>([])

  const fetchFanInfo = useCallback(async () => {
    try {
      const fans = await invoke<FanInfo[]>('get_fan_info')
      setFanList(fans)
    } catch (error) {
      console.error('获取风扇信息失败:', error)
    }
  }, [])

  useEffect(() => {
    fetchFanInfo()
  }, [fetchFanInfo])

  useInterval(fetchFanInfo, 2000)

  return (
    <div>
      <PageHeader title="风扇转速" subtitle="风扇运行状态监控" />

      <Card>
        <CardHeader>
          <CardHeaderTitle icon={<FanIcon className="h-4 w-4" />} iconClassName="bg-cyan-500/10 text-cyan-500" title="风扇状态" />
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[200px]">风扇名称</TableHead>
                <TableHead className="w-[150px]">当前转速</TableHead>
                <TableHead>转速状态</TableHead>
                <TableHead className="w-[120px]">控制模式</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {fanList.map((fan) => (
                <TableRow key={fan.name}>
                  <TableCell>{fan.name}</TableCell>
                  <TableCell>
                    <span className="font-bold text-blue-500">{fan.speed} RPM</span>
                  </TableCell>
                  <TableCell>
                    <Progress
                      value={getFanPercentage(fan.speed, fan.maxSpeed)}
                      className="h-2"
                      indicatorColor={getFanColor(fan.speed, fan.maxSpeed)}
                    />
                  </TableCell>
                  <TableCell>
                    <Badge variant={fan.mode === 'Auto' ? 'success' : 'info'}>{fan.mode}</Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

// src/views/Fan.vue
<template>
  <div class="fan">
    <div class="page-header">
      <div class="page-title-row">
        <h2 class="page-title">风扇转速</h2>
        <span class="page-subtitle">风扇运行状态监控</span>
      </div>
    </div>
    
    <el-card class="fan-card" shadow="never">
      <template #header>
        <div class="card-header">
          <div class="card-icon-badge fan">
            <el-icon :size="18"><WindPower /></el-icon>
          </div>
          <span>风扇状态</span>
        </div>
      </template>
      <el-table :data="fanList" style="width: 100%">
        <el-table-column prop="name" label="风扇名称" width="200" />
        <el-table-column prop="speed" label="当前转速" width="150">
          <template #default="scope">
            <span class="speed-value">{{ scope.row.speed }} RPM</span>
          </template>
        </el-table-column>
        <el-table-column label="转速状态">
          <template #default="scope">
            <el-progress :percentage="getFanPercentage(scope.row.speed, scope.row.maxSpeed)" :color="getFanColor(scope.row.speed, scope.row.maxSpeed)" :stroke-width="8" :show-text="false" />
          </template>
        </el-table-column>
        <el-table-column prop="mode" label="控制模式" width="120">
          <template #default="scope">
            <el-tag :type="scope.row.mode === 'Auto' ? 'success' : 'info'" size="small">{{ scope.row.mode }}</el-tag>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { invoke } from '@tauri-apps/api/tauri'

interface FanInfo {
  name: string
  speed: number
  maxSpeed: number
  mode: string
}

const fanList = ref<FanInfo[]>([])

let updateInterval: number | null = null

const getFanPercentage = (speed: number, maxSpeed: number) => {
  return Math.round((speed / maxSpeed) * 100)
}

const getFanColor = (speed: number, maxSpeed: number) => {
  const percentage = (speed / maxSpeed) * 100
  if (percentage < 30) return '#22c55e'
  if (percentage < 70) return '#f59e0b'
  return '#ef4444'
}

const fetchFanInfo = async () => {
  try {
    const fans = await invoke<FanInfo[]>('get_fan_info')
    fanList.value = fans
  } catch (error) {
    console.error('获取风扇信息失败:', error)
  }
}

onMounted(() => {
  fetchFanInfo()
  updateInterval = window.setInterval(fetchFanInfo, 2000)
})

onUnmounted(() => {
  if (updateInterval) {
    clearInterval(updateInterval)
  }
})
</script>

<style scoped>
.fan {
  color: #334155;
}

.page-header {
  margin-bottom: 20px;
}

.page-title-row {
  display: flex;
  align-items: baseline;
  gap: 12px;
}

.page-title {
  font-size: 22px;
  font-weight: 700;
  color: #1e293b;
  margin: 0;
}

.page-subtitle {
  font-size: 13px;
  color: #64748b;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  color: #1e293b;
  font-size: 15px;
  font-weight: 600;
}

.card-icon-badge {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
  background: rgba(6, 182, 212, 0.1);
  color: #06b6d4;
}

.speed-value {
  color: #3b82f6;
  font-weight: 700;
}
</style>
