// src/pages/Network.tsx
import { useCallback, useEffect, useState } from 'react'
import { Network as NetworkIcon, Send, Gauge, Download, Upload } from 'lucide-react'
import { toast } from 'sonner'
import { invoke } from '@/lib/tauri'
import { useInterval } from '@/hooks/use-interval'
import { PageHeader, CardHeaderTitle } from '@/components/page-header'
import { Descriptions } from '@/components/descriptions'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

interface NetworkInfo {
  ip: string
  subnet: string
  gateway: string
  dns: string
  mac: string
}

interface NetworkSpeed {
  download: string
  upload: string
}

export default function Network() {
  const [networkInfo, setNetworkInfo] = useState<NetworkInfo>({
    ip: '加载中...',
    subnet: '加载中...',
    gateway: '加载中...',
    dns: '加载中...',
    mac: '加载中...',
  })
  const [networkSpeed, setNetworkSpeed] = useState<NetworkSpeed>({ download: '0 KB/s', upload: '0 KB/s' })
  const [pingHost, setPingHost] = useState('')
  const [pingResult, setPingResult] = useState('')

  const fetchNetworkInfo = useCallback(async () => {
    try {
      const info = await invoke<NetworkInfo>('get_network_info')
      setNetworkInfo(info)
    } catch (error) {
      console.error('获取网络信息失败:', error)
    }
  }, [])

  const fetchNetworkSpeed = useCallback(async () => {
    try {
      const speed = await invoke<NetworkSpeed>('get_network_speed')
      setNetworkSpeed(speed)
    } catch (error) {
      console.error('获取网速失败:', error)
    }
  }, [])

  const runPing = async () => {
    if (!pingHost) {
      toast.warning('请输入主机地址')
      return
    }
    try {
      setPingResult('正在测试...')
      const result = await invoke<string>('run_ping', { host: pingHost })
      setPingResult(result)
    } catch (error) {
      setPingResult('测试失败: ' + error)
    }
  }

  useEffect(() => {
    fetchNetworkInfo()
    fetchNetworkSpeed()
  }, [fetchNetworkInfo, fetchNetworkSpeed])

  useInterval(fetchNetworkSpeed, 1000)

  return (
    <div>
      <PageHeader title="网络工具" subtitle="网络信息与测速" />

      <div className="grid grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <CardHeaderTitle icon={<NetworkIcon className="h-4 w-4" />} iconClassName="bg-blue-500/10 text-blue-500" title="网络信息" />
          </CardHeader>
          <CardContent>
            <Descriptions
              columns={1}
              items={[
                { label: 'IP 地址', value: networkInfo.ip },
                { label: '子网掩码', value: networkInfo.subnet },
                { label: '默认网关', value: networkInfo.gateway },
                { label: 'DNS 服务器', value: networkInfo.dns },
                { label: 'MAC 地址', value: networkInfo.mac },
              ]}
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardHeaderTitle icon={<Send className="h-4 w-4" />} iconClassName="bg-green-500/10 text-green-500" title="网络测试" />
          </CardHeader>
          <CardContent>
            <div className="p-5">
              <div className="mb-5 flex gap-2.5">
                <Input
                  value={pingHost}
                  onChange={(e) => setPingHost(e.target.value)}
                  placeholder="输入主机地址"
                  className="w-[200px]"
                />
                <Button onClick={runPing}>Ping</Button>
              </div>
              <div className="max-h-[200px] overflow-y-auto rounded-lg bg-slate-50 p-4">
                <pre className="m-0 whitespace-pre-wrap font-mono text-green-500">{pingResult}</pre>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="mt-4">
        <CardHeader>
          <CardHeaderTitle icon={<Gauge className="h-4 w-4" />} iconClassName="bg-orange-500/10 text-orange-500" title="实时网速" />
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-10">
            <div className="flex items-center gap-5 p-5">
              <Download className="h-11 w-11 text-green-500" />
              <div className="flex flex-col gap-1">
                <span className="text-sm text-slate-500">下载速度</span>
                <span className="text-2xl font-bold text-slate-800">{networkSpeed.download}</span>
              </div>
            </div>
            <div className="flex items-center gap-5 p-5">
              <Upload className="h-11 w-11 text-blue-500" />
              <div className="flex flex-col gap-1">
                <span className="text-sm text-slate-500">上传速度</span>
                <span className="text-2xl font-bold text-slate-800">{networkSpeed.upload}</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// src/views/Network.vue
<template>
  <div class="network">
    <div class="page-header">
      <div class="page-title-row">
        <h2 class="page-title">网络工具</h2>
        <span class="page-subtitle">网络信息与测速</span>
      </div>
    </div>
    
    <el-row :gutter="16">
      <el-col :span="12">
        <el-card class="tool-card" shadow="never">
          <template #header>
            <div class="card-header">
              <div class="card-icon-badge info">
                <el-icon :size="18"><Connection /></el-icon>
              </div>
              <span>网络信息</span>
            </div>
          </template>
          <el-descriptions :column="1" border>
            <el-descriptions-item label="IP 地址">{{ networkInfo.ip }}</el-descriptions-item>
            <el-descriptions-item label="子网掩码">{{ networkInfo.subnet }}</el-descriptions-item>
            <el-descriptions-item label="默认网关">{{ networkInfo.gateway }}</el-descriptions-item>
            <el-descriptions-item label="DNS 服务器">{{ networkInfo.dns }}</el-descriptions-item>
            <el-descriptions-item label="MAC 地址">{{ networkInfo.mac }}</el-descriptions-item>
          </el-descriptions>
        </el-card>
      </el-col>
      
      <el-col :span="12">
        <el-card class="tool-card" shadow="never">
          <template #header>
            <div class="card-header">
              <div class="card-icon-badge test">
                <el-icon :size="18"><Promotion /></el-icon>
              </div>
              <span>网络测试</span>
            </div>
          </template>
          <div class="test-tools">
            <div class="test-item">
              <el-input v-model="pingHost" placeholder="输入主机地址" style="width: 200px;" />
              <el-button type="primary" @click="runPing">Ping</el-button>
            </div>
            <div class="test-result">
              <pre>{{ pingResult }}</pre>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>
    
    <el-card class="speed-card" shadow="never" style="margin-top: 16px;">
      <template #header>
        <div class="card-header">
          <div class="card-icon-badge speed">
            <el-icon :size="18"><Odometer /></el-icon>
          </div>
          <span>实时网速</span>
        </div>
      </template>
      <el-row :gutter="40">
        <el-col :span="12">
          <div class="speed-item">
            <el-icon class="speed-icon download"><Download /></el-icon>
            <div class="speed-info">
              <span class="speed-label">下载速度</span>
              <span class="speed-value">{{ networkSpeed.download }}</span>
            </div>
          </div>
        </el-col>
        <el-col :span="12">
          <div class="speed-item">
            <el-icon class="speed-icon upload"><Upload /></el-icon>
            <div class="speed-info">
              <span class="speed-label">上传速度</span>
              <span class="speed-value">{{ networkSpeed.upload }}</span>
            </div>
          </div>
        </el-col>
      </el-row>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { ElMessage } from 'element-plus'
import { invoke } from '@tauri-apps/api/tauri'

interface NetworkInfo {
  ip: string
  subnet: string
  gateway: string
  dns: string
  mac: string
}

interface NetworkSpeed {
  download: string
  upload: string
}

const networkInfo = ref<NetworkInfo>({
  ip: '加载中...',
  subnet: '加载中...',
  gateway: '加载中...',
  dns: '加载中...',
  mac: '加载中...'
})

const networkSpeed = ref<NetworkSpeed>({
  download: '0 KB/s',
  upload: '0 KB/s'
})

const pingHost = ref('')
const pingResult = ref('')

let updateInterval: number | null = null

const fetchNetworkInfo = async () => {
  try {
    const info = await invoke<NetworkInfo>('get_network_info')
    networkInfo.value = info
  } catch (error) {
    console.error('获取网络信息失败:', error)
  }
}

const fetchNetworkSpeed = async () => {
  try {
    const speed = await invoke<NetworkSpeed>('get_network_speed')
    networkSpeed.value = speed
  } catch (error) {
    console.error('获取网速失败:', error)
  }
}

const runPing = async () => {
  if (!pingHost.value) {
    ElMessage.warning('请输入主机地址')
    return
  }
  
  try {
    pingResult.value = '正在测试...'
    const result = await invoke<string>('run_ping', { host: pingHost.value })
    pingResult.value = result
  } catch (error) {
    pingResult.value = '测试失败: ' + error
  }
}

onMounted(() => {
  fetchNetworkInfo()
  fetchNetworkSpeed()
  updateInterval = window.setInterval(fetchNetworkSpeed, 1000)
})

onUnmounted(() => {
  if (updateInterval) {
    clearInterval(updateInterval)
  }
})
</script>

<style scoped>
.network {
  color: #334155;
}

.page-header {
  margin-bottom: 20px;
}

.page-title-row {
  display: flex;
  align-items: baseline;
  gap: 12px;
}

.page-title {
  font-size: 22px;
  font-weight: 700;
  color: #1e293b;
  margin: 0;
}

.page-subtitle {
  font-size: 13px;
  color: #64748b;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  color: #1e293b;
  font-size: 15px;
  font-weight: 600;
}

.card-icon-badge {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
}

.card-icon-badge.info {
  background: rgba(59, 130, 246, 0.1);
  color: #3b82f6;
}

.card-icon-badge.test {
  background: rgba(34, 197, 94, 0.1);
  color: #22c55e;
}

.card-icon-badge.speed {
  background: rgba(249, 115, 22, 0.1);
  color: #f97316;
}

.test-tools {
  padding: 20px;
}

.test-item {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}

.test-result {
  background-color: #f8fafc;
  padding: 15px;
  border-radius: 8px;
  max-height: 200px;
  overflow-y: auto;
}

.test-result pre {
  margin: 0;
  color: #22c55e;
  font-family: monospace;
  white-space: pre-wrap;
}

.speed-item {
  display: flex;
  align-items: center;
  gap: 20px;
  padding: 20px;
}

.speed-icon {
  font-size: 44px;
}

.speed-icon.download {
  color: #22c55e;
}

.speed-icon.upload {
  color: #3b82f6;
}

.speed-info {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.speed-label {
  color: #64748b;
  font-size: 14px;
}

.speed-value {
  color: #1e293b;
  font-size: 24px;
  font-weight: 700;
}
</style>
