// src/pages/Startup.tsx
import { useEffect, useState } from 'react'
import { Star } from 'lucide-react'
import { toast } from 'sonner'
import { invoke } from '@/lib/tauri'
import { PageHeader, CardHeaderTitle } from '@/components/page-header'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

interface StartupItem {
  name: string
  publisher: string
  path: string
  enabled: boolean
}

export default function Startup() {
  const [startupItems, setStartupItems] = useState<StartupItem[]>([])

  const refreshList = async (showToast = true) => {
    try {
      const items = await invoke<StartupItem[]>('get_startup_items')
      setStartupItems(items)
      if (showToast) toast.success('刷新成功')
    } catch (error) {
      toast.error('获取启动项失败: ' + error)
    }
  }

  const toggleStartup = async (item: StartupItem, enabled: boolean) => {
    setStartupItems((prev) => prev.map((i) => (i.name === item.name ? { ...i, enabled } : i)))
    try {
      await invoke('toggle_startup', { name: item.name, enabled })
      toast.success(enabled ? '已启用' : '已禁用')
    } catch (error) {
      setStartupItems((prev) => prev.map((i) => (i.name === item.name ? { ...i, enabled: !enabled } : i)))
      toast.error('操作失败: ' + error)
    }
  }

  const deleteStartup = async (item: StartupItem) => {
    try {
      await invoke('delete_startup', { name: item.name })
      setStartupItems((prev) => prev.filter((i) => i.name !== item.name))
      toast.success('删除成功')
    } catch (error) {
      toast.error('删除失败: ' + error)
    }
  }

  useEffect(() => {
    refreshList(false)
  }, [])

  return (
    <div>
      <PageHeader title="启动项管理" subtitle="开机启动项管理" />

      <Card>
        <CardHeader>
          <CardHeaderTitle
            icon={<Star className="h-4 w-4" />}
            iconClassName="bg-amber-500/10 text-amber-500"
            title="启动项列表"
            action={
              <Button size="sm" onClick={() => refreshList(true)}>
                刷新
              </Button>
            }
          />
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[200px]">名称</TableHead>
                <TableHead className="w-[150px]">发布者</TableHead>
                <TableHead>路径</TableHead>
                <TableHead className="w-[100px]">状态</TableHead>
                <TableHead className="w-[150px]">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {startupItems.map((item) => (
                <TableRow key={item.name}>
                  <TableCell>{item.name}</TableCell>
                  <TableCell>{item.publisher}</TableCell>
                  <TableCell>{item.path}</TableCell>
                  <TableCell>
                    <Switch checked={item.enabled} onCheckedChange={(v) => toggleStartup(item, v)} />
                  </TableCell>
                  <TableCell>
                    <Button size="sm" variant="destructive" onClick={() => deleteStartup(item)}>
                      删除
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

// src/views/Startup.vue
<template>
  <div class="startup">
    <div class="page-header">
      <div class="page-title-row">
        <h2 class="page-title">启动项管理</h2>
        <span class="page-subtitle">开机启动项管理</span>
      </div>
    </div>
    
    <el-card class="startup-card" shadow="never">
      <template #header>
        <div class="card-header">
          <div class="card-icon-badge startup">
            <el-icon :size="18"><Star /></el-icon>
          </div>
          <span>启动项列表</span>
          <el-button type="primary" size="small" style="margin-left: auto;" @click="refreshList">刷新</el-button>
        </div>
      </template>
      <el-table :data="startupItems" style="width: 100%">
        <el-table-column prop="name" label="名称" width="200" />
        <el-table-column prop="publisher" label="发布者" width="150" />
        <el-table-column prop="path" label="路径" />
        <el-table-column prop="status" label="状态" width="100">
          <template #default="scope">
            <el-switch v-model="scope.row.enabled" @change="toggleStartup(scope.row)" />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150">
          <template #default="scope">
            <el-button type="danger" size="small" @click="deleteStartup(scope.row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { invoke } from '@tauri-apps/api/tauri'

interface StartupItem {
  name: string
  publisher: string
  path: string
  enabled: boolean
}

const startupItems = ref<StartupItem[]>([])

const refreshList = async () => {
  try {
    const items = await invoke<StartupItem[]>('get_startup_items')
    startupItems.value = items
    ElMessage.success('刷新成功')
  } catch (error) {
    ElMessage.error('获取启动项失败: ' + error)
  }
}

const toggleStartup = async (item: StartupItem) => {
  try {
    await invoke('toggle_startup', { name: item.name, enabled: item.enabled })
    ElMessage.success(item.enabled ? '已启用' : '已禁用')
  } catch (error) {
    ElMessage.error('操作失败: ' + error)
    item.enabled = !item.enabled
  }
}

const deleteStartup = async (item: StartupItem) => {
  try {
    await invoke('delete_startup', { name: item.name })
    startupItems.value = startupItems.value.filter(i => i.name !== item.name)
    ElMessage.success('删除成功')
  } catch (error) {
    ElMessage.error('删除失败: ' + error)
  }
}

onMounted(() => {
  refreshList()
})
</script>

<style scoped>
.startup {
  color: #334155;
}

.page-header {
  margin-bottom: 20px;
}

.page-title-row {
  display: flex;
  align-items: baseline;
  gap: 12px;
}

.page-title {
  font-size: 22px;
  font-weight: 700;
  color: #1e293b;
  margin: 0;
}

.page-subtitle {
  font-size: 13px;
  color: #64748b;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  color: #1e293b;
  font-size: 15px;
  font-weight: 600;
}

.card-icon-badge {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
  background: rgba(245, 158, 11, 0.1);
  color: #f59e0b;
}
</style>
