// src/views/Driver.vue
<template>
  <div class="driver">
    <div class="page-header">
      <div class="page-title-row">
        <h2 class="page-title">驱动管理</h2>
        <span class="page-subtitle">系统驱动扫描与更新</span>
      </div>
    </div>
    
    <el-card class="driver-card" shadow="never">
      <template #header>
        <div class="card-header">
          <div class="card-icon-badge driver">
            <el-icon :size="18"><SetUp /></el-icon>
          </div>
          <span>驱动列表</span>
          <el-button type="primary" size="small" style="margin-left: auto;" @click="scanDrivers">扫描驱动</el-button>
        </div>
      </template>
      <el-table :data="driverList" style="width: 100%">
        <el-table-column prop="name" label="驱动名称" width="250" />
        <el-table-column prop="version" label="版本" width="150" />
        <el-table-column prop="date" label="日期" width="120" />
        <el-table-column prop="publisher" label="发布者" width="150" />
        <el-table-column prop="status" label="状态" width="100">
          <template #default="scope">
            <el-tag :type="scope.row.status === '正常' ? 'success' : 'warning'" size="small">{{ scope.row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150">
          <template #default="scope">
            <el-button type="primary" size="small" @click="updateDriver(scope.row)">更新</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { invoke } from '@tauri-apps/api/tauri'

interface DriverItem {
  name: string
  version: string
  date: string
  publisher: string
  status: string
}

const driverList = ref<DriverItem[]>([])

const scanDrivers = async () => {
  try {
    const drivers = await invoke<DriverItem[]>('scan_drivers')
    driverList.value = drivers
    ElMessage.success('扫描完成')
  } catch (error) {
    ElMessage.error('扫描失败: ' + error)
  }
}

const updateDriver = async (driver: DriverItem) => {
  try {
    await invoke('update_driver', { name: driver.name })
    ElMessage.success('驱动更新已开始')
  } catch (error) {
    ElMessage.error('更新失败: ' + error)
  }
}

onMounted(() => {
  scanDrivers()
})
</script>

<style scoped>
.driver {
  color: #334155;
}

.page-header {
  margin-bottom: 20px;
}

.page-title-row {
  display: flex;
  align-items: baseline;
  gap: 12px;
}

.page-title {
  font-size: 22px;
  font-weight: 700;
  color: #1e293b;
  margin: 0;
}

.page-subtitle {
  font-size: 13px;
  color: #64748b;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  color: #1e293b;
  font-size: 15px;
  font-weight: 600;
}

.card-icon-badge {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
  background: rgba(59, 130, 246, 0.1);
  color: #3b82f6;
}
</style>

// src/pages/Driver.tsx
import { useEffect, useState } from 'react'
import { Settings2 } from 'lucide-react'
import { toast } from 'sonner'
import { invoke } from '@/lib/tauri'
import { PageHeader, CardHeaderTitle } from '@/components/page-header'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

interface DriverItem {
  name: string
  version: string
  date: string
  publisher: string
  status: string
}

export default function Driver() {
  const [driverList, setDriverList] = useState<DriverItem[]>([])

  const scanDrivers = async (showToast = true) => {
    try {
      const drivers = await invoke<DriverItem[]>('scan_drivers')
      setDriverList(drivers)
      if (showToast) toast.success('扫描完成')
    } catch (error) {
      toast.error('扫描失败: ' + error)
    }
  }

  const updateDriver = async (driver: DriverItem) => {
    try {
      await invoke('update_driver', { name: driver.name })
      toast.success('驱动更新已开始')
    } catch (error) {
      toast.error('更新失败: ' + error)
    }
  }

  useEffect(() => {
    scanDrivers(false)
  }, [])

  return (
    <div>
      <PageHeader title="驱动管理" subtitle="系统驱动扫描与更新" />

      <Card>
        <CardHeader>
          <CardHeaderTitle
            icon={<Settings2 className="h-4 w-4" />}
            iconClassName="bg-blue-500/10 text-blue-500"
            title="驱动列表"
            action={
              <Button size="sm" onClick={() => scanDrivers(true)}>
                扫描驱动
              </Button>
            }
          />
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[250px]">驱动名称</TableHead>
                <TableHead className="w-[150px]">版本</TableHead>
                <TableHead className="w-[120px]">日期</TableHead>
                <TableHead className="w-[150px]">发布者</TableHead>
                <TableHead className="w-[100px]">状态</TableHead>
                <TableHead className="w-[150px]">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {driverList.map((driver) => (
                <TableRow key={driver.name}>
                  <TableCell>{driver.name}</TableCell>
                  <TableCell>{driver.version}</TableCell>
                  <TableCell>{driver.date}</TableCell>
                  <TableCell>{driver.publisher}</TableCell>
                  <TableCell>
                    <Badge variant={driver.status === '正常' ? 'success' : 'warning'}>{driver.status}</Badge>
                  </TableCell>
                  <TableCell>
                    <Button size="sm" onClick={() => updateDriver(driver)}>
                      更新
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
